"use client";
import { useEffect, useState, useRef } from 'react';
import { ArrowRight, ArrowUpRight, Check, Code2, Zap, ShieldCheck, Clock3, Layers, Menu, X, Rocket, Bot, ChartNoAxesCombined, Smartphone, Database, Globe, Workflow, Plus, Minus, Download, ChevronRight, Activity, LockKeyhole, Terminal, HeartPulse, ShoppingBag, Building2, Scale, CreditCard, Megaphone, Package, BriefcaseBusiness } from 'lucide-react';
import { WorkExamples } from '@/components/work-examples';
import {ReferenceSite} from '@/components/reference-site';
import Brand from '@/components/brand';
import { ExpandedPage } from '@/components/expanded-pages';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
const industries=[{name:'Healthcare & MedTech',icon:HeartPulse,desc:'Patient portals, appointment workflows, and clinical operations tools.',tags:['React','Scheduling','Portals'],cat:'Platforms'},{name:'Sales & revenue automation',icon:Bot,desc:'Lead research, CRM workflows, follow-ups, and voice-enabled sales experiences.',tags:['AI agents','CRM','Twilio'],cat:'AI & automation'},{name:'Developer tools & AI',icon:Terminal,desc:'Internal copilots, developer workflows, and tools that remove repetitive work.',tags:['APIs','Node.js','AI'],cat:'AI & automation'},{name:'Marketing & agency SaaS',icon:Megaphone,desc:'Content planning, campaign management, and reporting in one place.',tags:['Analytics','CMS','Automation'],cat:'Platforms'},{name:'Events & logistics',icon:Package,desc:'Vendor coordination, booking systems, and real-time operations.',tags:['Scheduling','PostgreSQL'],cat:'Platforms'},{name:'E-commerce & retail',icon:ShoppingBag,desc:'Product discovery, customer support, and order automation.',tags:['Commerce','AI chat','Payments'],cat:'Commerce'},{name:'B2B SaaS & platforms',icon:BriefcaseBusiness,desc:'Focused software products with accounts, dashboards, and subscriptions.',tags:['Auth','Billing','Full stack'],cat:'Platforms'},{name:'Real estate technology',icon:Building2,desc:'Property inquiries, lead qualification, and connected agent workflows.',tags:['Voice AI','CRM sync'],cat:'AI & automation'},{name:'Legal technology',icon:Scale,desc:'Document workflows, case organization, and assisted information extraction.',tags:['Documents','Search','LLMs'],cat:'AI & automation'},{name:'Fintech & reporting',icon:CreditCard,desc:'Payment experiences, financial dashboards, and reporting workflows.',tags:['Payments','Dashboards'],cat:'Commerce'}];
const extras=[{name:'Advanced AI features',desc:'LLM integrations, embeddings, RAG, and agents.',icon:Bot,group:0},{name:'Mobile apps',desc:'iOS and Android with a shared React Native codebase.',icon:Smartphone,group:0},{name:'Custom dashboard',desc:'A branded admin experience with role-based access.',icon:ChartNoAxesCombined,group:1},{name:'API integration',desc:'Connect an external service to your product.',icon:Workflow,group:1},{name:'Launch roadmap',desc:'A 30/60/90-day plan with clear product priorities.',icon:Rocket,group:2},{name:'Product Hunt prep',desc:'Launch assets, copy, hunter outreach, and a launch-day plan.',icon:Globe,group:2}];

function Eyebrow({children}:{children:React.ReactNode}){return <div className="eyebrow"><span/>{children}</div>}
export default function Home({initialRoute=''}:{initialRoute?:string}){
const [menu,setMenu]=useState(false),[selected,setSelected]=useState<number[]>([]),[modal,setModal]=useState(false),[detail,setDetail]=useState<number|null>(null),[route,setRoute]=useState(initialRoute),[filter,setFilter]=useState('All projects'),[phase,setPhase]=useState(1),[progress,setProgress]=useState(0),[saved,setSaved]=useState(false),[form,setForm]=useState({name:'',email:'',idea:''});
const [sending,setSending]=useState(false),[sendError,setSendError]=useState(''),[reference,setReference]=useState(''),[consent,setConsent]=useState(false),[website,setWebsite]=useState(''); const requestId=useRef('');
const total=selected.length;
useEffect(()=>{const change=()=>{setRoute(location.hash.startsWith('#/')?location.hash.slice(2):initialRoute);setMenu(false);if(location.hash.startsWith('#/'))window.scrollTo({top:0,behavior:'instant'});else requestAnimationFrame(()=>requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView({behavior:'smooth'})));};change();window.addEventListener('hashchange',change);let frame=0;const onScroll=()=>{if(frame)return;frame=requestAnimationFrame(()=>{setProgress(window.scrollY/Math.max(1,document.documentElement.scrollHeight-window.innerHeight)*100);frame=0})};window.addEventListener('scroll',onScroll,{passive:true});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>{if(e.getBoundingClientRect().top>innerHeight)e.classList.add('motion-ready');io.observe(e)});return()=>{window.removeEventListener('hashchange',change);window.removeEventListener('scroll',onScroll);cancelAnimationFrame(frame);io.disconnect()}},[route,initialRoute]);
useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const t=setInterval(()=>setPhase(p=>(p+1)%4),6500);return()=>clearInterval(t)},[]);
const submit=async(e:React.FormEvent)=>{e.preventDefault();if(sending||saved)return;setSending(true);setSendError('');try{if(!requestId.current){const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,v=>v.toString(16).padStart(2,'0')).join('');requestId.current=h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20);}const res=await fetch('/api/inquiries',{signal:AbortSignal.timeout(20000),method:'POST',headers:{'Content-Type':'application/json','X-Jinnx-Request':'1'},body:JSON.stringify({id:requestId.current,...form,addons:selected,consent,website})});const data=await res.json() as {error?:string;reference:string};if(!res.ok)throw new Error(data.error||'Unable to send your inquiry. Please try again.');setReference(data.reference);setSaved(true)}catch(e){setSendError(e instanceof Error?e.message:'Connection lost. Your details are still here. Please try again.')}finally{setSending(false)}};

const toggle=(i:number)=>setSelected(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i]);
const download=(e:React.FormEvent)=>{e.preventDefault();const text='Jinnx Automation | Project brief\n\nName: '+form.name+'\nEmail: '+form.email+'\n\nWhat you want to automate or build:\n'+form.idea+'\n\nInterests:\n'+(selected.map(i=>extras[i].name).join('\n')||'(none marked)')+'\n\nThis is a locally prepared brief, not a submitted inquiry or confirmed booking. Scope and terms are agreed in a written proposal.';const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='Jinnx Automation-project-brief.txt';a.click();URL.revokeObjectURL(url)};
const open=()=>{if(saved){setForm({name:'',email:'',idea:''});setConsent(false)}setSaved(false);setSendError('');setReference('');requestId.current='';setModal(true)};
return <>{(!route||route==='portfolio')?<ReferenceSite route={route} selected={selected} total={total} onToggle={toggle} onContact={open}/>:<><div className="reading-progress" style={{width:progress+'%'}}/><header className="site-header"><div className="nav-wrap"><Brand/><nav className={menu?'nav-links is-open':'nav-links'} aria-label="Main navigation">{[['Services','/services'],['How we work','/process'],['Our approach','/about'],['Work','/work'],['Resources','/resources'],['Pricing','/#pricing']].map(([n,l])=><a key={n} href={l} onClick={()=>setMenu(false)}>{n}</a>)}</nav><a className="button dark nav-cta" href="/#pricing">Start your project <ArrowUpRight size={16}/></a><Button className="menu-toggle" variant="ghost" size="icon" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div></header>
{['services','process','about','resources','contact'].includes(route)||route.startsWith('services/')||route.startsWith('resources/')?<ExpandedPage route={route} onContact={open}/>:route==='portfolio'?<WorkExamples onContact={open}/>:route==='privacy'||route==='terms'?<main className="legal-page wrap"><a className="back-link" href="/#top">← Back to home</a><Eyebrow>JINNX AUTOMATION</Eyebrow><h1>{route==='privacy'?'Privacy notice':'Preview terms'}</h1>{route==='privacy'?<><h3>Your inquiry goes to our private inbox.</h3><p>When you submit an inquiry, we store your name, email, project description, selected package, and submission time to review and respond to your request. Private follow-up notes are visible only to the site owner.</p><h3>Services used by this preview</h3><p>This site is hosted through ChatGPT Sites. Font files may be loaded from Google Fonts. Those providers may receive ordinary connection information such as your IP address.</p><h3>Managing your information</h3><p>You can request a correction or removal of your inquiry by replying to our correspondence. We use short-lived request counters to limit abuse. Submitting an inquiry does not subscribe you to marketing.</p></>:<><h3>A demonstration of the proposed service</h3><p>Prices, timelines, and package contents are illustrative for this preview. They are not a binding offer. Final commercial terms require a separate written agreement with Jinnx Automation.</p><h3>Project briefs and bookings</h3><p>Submitting the form sends an inquiry to our inbox. It does not reserve availability, confirm a booking, or create an obligation to pay. No payments are collected here.</p><h3>Portfolio concepts</h3><p>Portfolio entries illustrate potential applications. They do not represent completed client projects or verified outcomes.</p></>}</main>:null}
<footer><div className="wrap"><div className="footer-top"><Brand/><p>Intelligent products. Thoughtful automation.<br/>Built to move your business forward.</p><a className="button dark" href="/#pricing">Let’s build <ArrowUpRight size={17}/></a></div><div className="footer-links"><div><span className="mono">PRODUCT</span><a href="/services">Our services</a><a href="/about">About Jinnx Automation</a><a href="/process">How we work</a><a href="/#pricing">Pricing builder</a></div><div><span className="mono">EXPLORE</span><a href="/work">Portfolio concepts</a><a href="/#industries">Industries</a><a href="/resources">Guides & resources</a><a href="/resources/tech-stack-guide">Tech stack guide</a><a href="/resources/founder-launch-playbook">Founder playbook</a><a href="/#capacity">Availability & consultation</a><a href="/contact">Contact us</a><a href="/#faq">Common questions</a></div><div><div className="jinnx-contact-details"><h3>Contact</h3><p><a href="tel:+18884863840">+1 888 486 3840</a> (US)</p><p><a href="tel:+442033497819">+44 20 3349 7819</a> (UK)</p><p><a href="mailto:info@jinnxautomation.com">info@jinnxautomation.com</a></p><p>Mon–Fri, 9am–6pm CT</p><h3>Offices</h3><p>1016 W Jackson Blvd, Chicago, IL 60607</p><p>3 Fitzroy Pl, Finnieston, Glasgow G3 7RH</p></div><span className="mono">LET’S MAKE IT HAPPEN</span><p>A good idea is a great place to start.<br/>A working product is even better.</p><button className="text-link" onClick={open}>Start your project inquiry <ArrowUpRight size={17}/></button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Jinnx Automation.</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/admin">Admin</a><a href="/#top">Back to top ↑</a></div></div></div></footer></>}
<Dialog open={modal} onOpenChange={v=>{if(!sending)setModal(v)}}><DialogContent className="brief-modal"><Eyebrow>LET’S MAKE IT REAL</Eyebrow><DialogTitle className="modal-title">Your next big thing.</DialogTitle><DialogDescription>Tell us what you have in mind. Your inquiry goes directly to our private inbox, and we’ll follow up by email.</DialogDescription><form onSubmit={submit}><label htmlFor="name">Your name</label><Input id="name" disabled={sending||saved} minLength={2} maxLength={100} autoComplete="name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Alex Morgan"/><label htmlFor="email">Email address</label><Input id="email" disabled={sending||saved} maxLength={254} autoComplete="email" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="alex@company.com"/><label htmlFor="idea">What would you like to build?</label><Textarea id="idea" disabled={sending||saved} minLength={20} maxLength={6000} required value={form.idea} onChange={e=>setForm({...form,idea:e.target.value})} placeholder="The idea, the people it helps, and the one thing it needs to do well…"/><div className="form-honeypot" aria-hidden="true"><label htmlFor="company-website">Website</label><input id="company-website" tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></div><div className="consent-row"><Checkbox id="inquiry-consent" checked={consent} disabled={sending||saved} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor="inquiry-consent">I agree to the <a href="/privacy" target="_blank" rel="noopener">privacy notice</a> and to being contacted about this project.</label></div><Button type="submit" disabled={sending||saved||!consent} className="button orange-btn">{saved?<Check size={18}/>:<ArrowUpRight size={18}/>} {sending?'Sending your inquiry…':saved?'Inquiry received':'Send my inquiry'}</Button><Button type="button" variant="ghost" onClick={download}><Download size={16}/> Keep a copy of my brief</Button>{sendError&&<p className="form-error" role="alert">{sendError}</p>}{saved&&<div className="inquiry-success" role="status"><Check size={20}/><div><strong>You’re in our inbox.</strong><p>We’ll reply to {form.email} about your project.</p><small>Reference: {reference.slice(0,8).toUpperCase()}</small></div></div>}</form></DialogContent></Dialog>
<Dialog open={detail!==null} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="brief-modal"><Eyebrow>ILLUSTRATIVE PROJECT CONCEPT</Eyebrow><DialogTitle className="modal-title">{detail!==null&&industries[detail].name}</DialogTitle><DialogDescription>{detail!==null&&industries[detail].desc}</DialogDescription><h4>A focused first release could include</h4><ul className="concept-features"><li><Check/> A clear, responsive core user journey</li><li><Check/> The data and integrations your workflow needs</li><li><Check/> A practical admin interface</li><li><Check/> Deployment and source-code handoff</li></ul><p>We define the exact features and delivery target during discovery. This is a potential application, not a published client case study.</p><Button className="button orange-btn" onClick={()=>{setDetail(null);open()}}>Build something like this <ArrowUpRight size={17}/></Button></DialogContent></Dialog>
</>}
