'use client';
import React,{createElement,useEffect,useRef,useState} from 'react';
import templates from '@/lib/reference-templates.json';
import {projects} from '@/components/work-examples';
import {addonNames} from '@/lib/inquiries';
import {ArrowRight,Plus,Check,X,Menu} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
type Tree=string|{tag:string;props:Record<string,any>;children:Tree[]};
const plain=(node:Tree):string=>typeof node==='string'?node:node.children.map(plain).join('');
function PlanningCountdown(){const [cells,setCells]=useState(['—','—','—','—']);useEffect(()=>{const tick=()=>{const now=new Date();const next=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1));let s=Math.max(0,Math.floor((next.getTime()-now.getTime())/1000));setCells([Math.floor(s/86400),Math.floor(s%86400/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')))};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[]);return <div className="countdown-grid" aria-label="Time until next calendar month">{cells.map((x,i)=><div className="countdown-cell" key={i}><div className="num">{x}</div><div className="lbl">{['Days','Hours','Minutes','Seconds'][i]}</div></div>)}</div>}
// Every page shares the home page's nav and footer. Home and portfolio render
// their full templates; plan and faq are assembled from home sections; any
// other route passes its content as children between the same chrome.
export function ReferenceSite({route,selected,total,onToggle,onContact,children}:{route:string;selected:number[];total:number;onToggle:(i:number)=>void;onContact:()=>void;children?:React.ReactNode}){
 const page=route==='portfolio'?'portfolio':route==='plan'?'plan':route==='faq'?'faq':'home';const root=useRef<HTMLDivElement>(null);const [menu,setMenu]=useState(false),[filter,setFilter]=useState('All work'),[detail,setDetail]=useState<number|null>(null);
 const [faq,setFaq]=useState('faq-0');const home=templates.home as unknown as Tree[];const nav=home[0],footer=home[13];
 const trees:Tree[]=page==='plan'?[nav,home[8],home[9],footer]:page==='faq'?[nav,home[11],home[12],footer]:templates[page] as unknown as Tree[];
 useEffect(()=>{const box=root.current;if(!box)return;const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.07});box.querySelectorAll('.reveal').forEach(e=>io.observe(e));const update=()=>box.querySelector('.nav')?.classList.toggle('scrolled',window.scrollY>20);update();window.addEventListener('scroll',update,{passive:true});return()=>{io.disconnect();window.removeEventListener('scroll',update)}},[page,filter]);
 // The plan summary lists what the visitor marked. No prices are shown anywhere; scope and terms come in a written proposal.
 const summary=()=> <aside className="summary"><div className="summary-head"><span>Your automation plan</span><span className="ticker"><span className="live-dot"/> live</span></div><div className="summary-row"><span className="k">Discovery call and written plan</span><span className="v"><Check size={13}/></span></div>{selected.length?selected.map(i=><div className="summary-row" key={i}><span className="k">{addonNames[i]}</span><button className="reference-remove" aria-label={'Remove '+addonNames[i]} onClick={()=>onToggle(i)}><X size={13}/></button></div>):<div className="summary-empty"><Plus size={12}/> Tap any <em>+ Add</em> card to shape your plan</div>}<div className="summary-total"><div className="lbl">Areas selected</div><div className="price" aria-live="polite">{total}</div><div className="save-bar"><div className="save-bar-track"><div className="save-bar-fill" style={{width:'100%'}}/></div><div className="save">Your process. Your approval. Your data.</div></div></div><Button className="btn btn-orange btn-lg" style={{width:'100%',marginTop:20}} onClick={onContact}>Discuss this plan <ArrowRight size={16}/></Button><div className="summary-trust"><span><Check size={11}/> No card</span><span><Check size={11}/> NDA</span><span><Check size={11}/> Written proposal</span></div><p className="reference-summary-note">Scope, schedule, and terms are confirmed in your proposal after a discovery call.</p></aside>;
 function render(n:Tree,key:string):React.ReactNode{
  if(typeof n==='string')return n;
  const p:Record<string,any>={...n.props,key};const cls=String(p.className||'');const component=p['data-component'];
  if(component==='summary')return <React.Fragment key={key}>{summary()}</React.Fragment>;
  if(component==='countdown')return <PlanningCountdown key={key}/>;
  if(component==='mobile')return menu?<div className="nav-mobile open" key={key}><div className="container nav-mobile-inner">{[['Services','/services'],['Solution','/#solution'],['How It Works','/#journey'],['Portfolio','/work'],['Your Plan','/#pricing'],['FAQ','/#faq']].map(([label,url])=><a key={url} href={url} onClick={()=>setMenu(false)}>{label}<ArrowRight size={16}/></a>)}<a className="btn btn-orange nav-mobile-cta" href="/#pricing" onClick={()=>setMenu(false)}>Start your project <ArrowRight size={16}/></a></div></div>:null;
  if(cls==='faq-list')return <Accordion type="single" collapsible value={faq} onValueChange={setFaq} className="faq-list" key={key}>{n.children.map((c,i)=>render(c,key+'.'+i))}</Accordion>;
  if(component==='faq'){const i=Number(p['data-index']);const question=n.children.find(c=>typeof c!=='string'&&c.props.className==='faq-q');const answer=n.children.find(c=>typeof c!=='string'&&c.props.className==='faq-a');return <AccordionItem value={'faq-'+i} className={'faq-item '+(faq==='faq-'+i?'open':'')} key={key}><AccordionTrigger className="faq-q"><span>{question?plain(question):''}</span><span className="faq-toggle"><Plus size={14}/></span></AccordionTrigger><AccordionContent className="faq-a">{answer?plain(answer):''}</AccordionContent></AccordionItem>}
  if(component==='project'&&filter!=='All work'&&!String(p['data-categories']).split('|').includes(filter))return null;
  if(p['data-addon']!==undefined){const i=Number(p['data-addon']);const active=selected.includes(i);p.onClick=()=>onToggle(i);p['aria-pressed']=active;p.className='tier-opt '+(active?'is-selected':'is-add');p['aria-label']=(active?'Remove ':'Add ')+addonNames[i];return createElement('button',p,<><div className="tier-opt-marker">{active?<Check size={11}/>:<Plus size={11}/>}</div>{n.children.filter(c=>typeof c!=='string'&&['opt-name','opt-desc'].includes(c.props.className)).map((c,j)=>render(c,key+'.'+j))}<div className="opt-price"><span className="opt-price-paid">{active?<Check size={10}/>:<Plus size={10}/>} {active?'Added to your plan':'Add to your plan'}</span></div></>)}
  if(p['data-filter']){p.onClick=()=>setFilter(p['data-filter']);p.className='filter-chip '+(filter===p['data-filter']?'active':'');p['aria-pressed']=filter===p['data-filter']}
  if(p['data-case']!==undefined)p.onClick=()=>setDetail(Number(p['data-case']));
  if(p['data-action']==='contact')p.onClick=onContact;
  if(p['data-action']==='menu'){p.onClick=()=>setMenu(!menu);p['aria-expanded']=menu;p['aria-label']=menu?'Close menu':'Open menu';return createElement('button',p,menu?<X size={20}/>:<Menu size={20}/>)}
  if(p['data-action']==='portfolio'){p.onClick=()=>{window.location.href='/work'};p.onKeyDown=(e:React.KeyboardEvent)=>{if(e.key==='Enter')window.location.href='/work'}}
  if(cls==='filter-status'){const findCards=(items:Tree[]):Tree[]=>items.flatMap(t=>typeof t==='string'?[]:t.props['data-project']!==undefined?[t]:findCards(t.children));const num=filter==='All work'?10:findCards(trees).filter(t=>typeof t!=='string'&&String(t.props['data-categories']).split('|').includes(filter)).length;return <div className="filter-status" aria-live="polite" key={key}><span className="dot"/>Showing {num} of 10</div>}
  return createElement(n.tag,p,n.children.length?n.children.map((c,i)=>render(c,key+'.'+i)):undefined);
 }
 const item=detail!==null?projects[detail]:null;
 return <>{children?<><div ref={root} className="reference-site">{render(nav,'nav')}</div>{children}<div className="reference-site">{render(footer,'footer')}</div></>:<div ref={root} className="reference-site">{trees.map((n,i)=>render(n,String(i)))}</div>}<Dialog open={!!item} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="brief-modal reference-case-dialog"><div className="eyebrow"><span/>JINNX AUTOMATION / SOLUTION DETAILS</div><DialogTitle className="modal-title">{item?.name}</DialogTitle><DialogDescription>{item?.summary}</DialogDescription><h4>What a first release could include</h4><ul className="concept-features">{item?.features.map(f=><li key={f}><Check size={17}/>{f}</li>)}</ul><div className="tech-tags">{item?.stack.map(t=><span key={t}>{t}</span>)}</div><p>{item?.boundary}</p><p>This is a solution concept. Your proposal defines the exact scope, delivery, and support arrangements.</p><Button className="button orange-btn" onClick={()=>{setDetail(null);onContact()}}>Build a solution like this <ArrowRight size={17}/></Button></DialogContent></Dialog></>;
}
