'use client';
import React,{createElement,useEffect,useRef,useState} from 'react';
import templates from '@/lib/reference-templates.json';
import {projects} from '@/components/work-examples';
import {ArrowRight,Plus,Check,X,Menu} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
type Tree=string|{tag:string;props:Record<string,any>;children:Tree[]};
const extras=[['Advanced AI features',1000],['Mobile apps',1500],['Custom dashboard',500],['API integration',300],['Launch roadmap',250],['Product Hunt prep',400]] as const;
const cash=(n:number)=>'$'+n.toLocaleString('en-US');
const plain=(node:Tree):string=>typeof node==='string'?node:node.children.map(plain).join('');
function PlanningCountdown(){const [cells,setCells]=useState(['—','—','—','—']);useEffect(()=>{const tick=()=>{const now=new Date();const next=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1));let s=Math.max(0,Math.floor((next.getTime()-now.getTime())/1000));setCells([Math.floor(s/86400),Math.floor(s%86400/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')))};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[]);return <div className="countdown-grid" aria-label="Time until next calendar month">{cells.map((x,i)=><div className="countdown-cell" key={i}><div className="num">{x}</div><div className="lbl">{['Days','Hours','Minutes','Seconds'][i]}</div></div>)}</div>}
export function ReferenceSite({route,selected,total,onToggle,onContact}:{route:string;selected:number[];total:number;onToggle:(i:number)=>void;onContact:()=>void}){
 const page=route==='portfolio'?'portfolio':'home';const root=useRef<HTMLDivElement>(null);const [menu,setMenu]=useState(false),[filter,setFilter]=useState('All work'),[detail,setDetail]=useState<number|null>(null);
 const [faq,setFaq]=useState('faq-0');const trees=templates[page] as unknown as Tree[];
 useEffect(()=>{const box=root.current;if(!box)return;const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.07});box.querySelectorAll('.reveal').forEach(e=>io.observe(e));const update=()=>box.querySelector('.nav')?.classList.toggle('scrolled',window.scrollY>20);update();window.addEventListener('scroll',update,{passive:true});return()=>{io.disconnect();window.removeEventListener('scroll',update)}},[page,filter]);
 const summary=()=> <aside className="summary"><div className="summary-head"><span>Your custom package</span><span className="ticker"><span className="live-dot"/> live</span></div><div className="summary-row"><span className="k">Base product · 100 hours</span><span className="v">$10,999</span></div>{selected.length?selected.map(i=><div className="summary-row" key={i}><span className="k">{extras[i][0]}</span><span className="v">{cash(extras[i][1])}</span><button className="reference-remove" aria-label={'Remove '+extras[i][0]} onClick={()=>onToggle(i)}><X size={13}/></button></div>):<div className="summary-empty"><Plus size={12}/> Tap any <em>+ Add</em> card to shape your package</div>}<div className="summary-total"><div className="lbl">Your total estimate</div><div className="price" aria-live="polite">{cash(total)}</div><div className="save-bar"><div className="save-bar-track"><div className="save-bar-fill" style={{width:'100%'}}/></div><div className="save">Your scope. Your code. Your product.</div></div></div><Button className="btn btn-orange btn-lg" style={{width:'100%',marginTop:20}} onClick={onContact}>Discuss this package <ArrowRight size={16}/></Button><div className="summary-trust"><span><Check size={11}/> No card</span><span><Check size={11}/> NDA</span><span><Check size={11}/> Contract terms</span></div><div className="summary-crypto"><span>Eligible crypto payment · 5% off</span><span className="b">{cash(Math.round(total*.95*100)/100)}</span></div><p className="reference-summary-note">Scope, schedule, payment fees, and refund conditions are confirmed in your proposal.</p></aside>;
 function render(n:Tree,key:string):React.ReactNode{
  if(typeof n==='string')return n;
  const p:Record<string,any>={...n.props,key};const cls=String(p.className||'');const component=p['data-component'];
  if(component==='summary')return <React.Fragment key={key}>{summary()}</React.Fragment>;
  if(component==='countdown')return <PlanningCountdown key={key}/>;
  if(component==='mobile')return menu?<div className="nav-mobile open" key={key}><div className="container nav-mobile-inner">{[['Solution','/#solution'],['How It Works','/#journey'],['Portfolio','/work'],['Pricing','/#pricing'],['FAQ','/#faq']].map(([label,url])=><a key={url} href={url} onClick={()=>setMenu(false)}>{label}<ArrowRight size={16}/></a>)}<a className="btn btn-orange nav-mobile-cta" href="/#pricing" onClick={()=>setMenu(false)}>Start your project <ArrowRight size={16}/></a></div></div>:null;
  if(cls==='faq-list')return <Accordion type="single" collapsible value={faq} onValueChange={setFaq} className="faq-list" key={key}>{n.children.map((c,i)=>render(c,key+'.'+i))}</Accordion>;
  if(component==='faq'){const i=Number(p['data-index']);const question=n.children.find(c=>typeof c!=='string'&&c.props.className==='faq-q');const answer=n.children.find(c=>typeof c!=='string'&&c.props.className==='faq-a');return <AccordionItem value={'faq-'+i} className={'faq-item '+(faq==='faq-'+i?'open':'')} key={key}><AccordionTrigger className="faq-q"><span>{question?plain(question):''}</span><span className="faq-toggle"><Plus size={14}/></span></AccordionTrigger><AccordionContent className="faq-a">{answer?plain(answer):''}</AccordionContent></AccordionItem>}
  if(component==='project'&&filter!=='All work'&&!String(p['data-categories']).split('|').includes(filter))return null;
  if(p['data-addon']!==undefined){const i=Number(p['data-addon']);const active=selected.includes(i);p.onClick=()=>onToggle(i);p['aria-pressed']=active;p.className='tier-opt '+(active?'is-selected':'is-add');p['aria-label']=(active?'Remove ':'Add ')+extras[i][0]+' for '+cash(extras[i][1]);return createElement('button',p,<><div className="tier-opt-marker">{active?<Check size={11}/>:<Plus size={11}/>}</div>{n.children.filter(c=>typeof c!=='string'&&['opt-name','opt-desc'].includes(c.props.className)).map((c,j)=>render(c,key+'.'+j))}<div className="opt-price"><span className="opt-price-paid">{active?<Check size={10}/>:<Plus size={10}/>} {active?'Added':'Add'} · +{cash(extras[i][1])}</span></div></>)}
  if(p['data-filter']){p.onClick=()=>setFilter(p['data-filter']);p.className='filter-chip '+(filter===p['data-filter']?'active':'');p['aria-pressed']=filter===p['data-filter']}
  if(p['data-case']!==undefined)p.onClick=()=>setDetail(Number(p['data-case']));
  if(p['data-action']==='contact')p.onClick=onContact;
  if(p['data-action']==='menu'){p.onClick=()=>setMenu(!menu);p['aria-expanded']=menu;p['aria-label']=menu?'Close menu':'Open menu';return createElement('button',p,menu?<X size={20}/>:<Menu size={20}/>)}
  if(p['data-action']==='portfolio'){p.onClick=()=>{window.location.href='/work'};p.onKeyDown=(e:React.KeyboardEvent)=>{if(e.key==='Enter')window.location.href='/work'}}
  if(cls==='filter-status'){const findCards=(items:Tree[]):Tree[]=>items.flatMap(t=>typeof t==='string'?[]:t.props['data-project']!==undefined?[t]:findCards(t.children));const num=filter==='All work'?10:findCards(trees).filter(t=>typeof t!=='string'&&String(t.props['data-categories']).split('|').includes(filter)).length;return <div className="filter-status" aria-live="polite" key={key}><span className="dot"/>Showing {num} of 10</div>}
  return createElement(n.tag,p,n.children.length?n.children.map((c,i)=>render(c,key+'.'+i)):undefined);
 }
 const item=detail!==null?projects[detail]:null;
 return <><div ref={root} className="reference-site">{trees.map((n,i)=>render(n,String(i)))}</div><Dialog open={!!item} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="brief-modal reference-case-dialog"><div className="eyebrow"><span/>JINNX AUTOMATION / SOLUTION DETAILS</div><DialogTitle className="modal-title">{item?.name}</DialogTitle><DialogDescription>{item?.summary}</DialogDescription><h4>Features in a focused first release</h4><ul className="concept-features">{item?.features.map(f=><li key={f}><Check size={17}/>{f}</li>)}</ul><div className="tech-tags">{item?.stack.map(t=><span key={t}>{t}</span>)}</div><p>{item?.boundary}</p><p>This is a solution concept. Your proposal defines the exact scope, delivery, and support arrangements.</p><Button className="button orange-btn" onClick={()=>{setDetail(null);onContact()}}>Build a solution like this <ArrowRight size={17}/></Button></DialogContent></Dialog></>;
}
